version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: steelplant_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log

  influxdb:
    image: influxdb:2.7
    container_name: steelplant_influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./docker/influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}

  grafana:
    image: grafana/grafana:10.4.5
    container_name: steelplant_grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/var/lib/grafana
